// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvrvhjxcqsjvrcdaffly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cnZoanhjcXNqdnJjZGFmZmx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDMxNDcsImV4cCI6MjA3MDUxOTE0N30.e4pidn1YNTHZy6kQyxY3NidsUcY5q2fd_mhISFmwvnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});